paths:
  predictors_dir: /scratch3/plant-traits-v2/data/1km/predictors_processed/
  targets_dir: /scratch3/plant-traits-v2/data/1km/targets/
  splits_file: /scratch3/plant-traits-v2/data/1km/splits/h3_splits_res2_1km.gpkg
  zarr_dir: /scratch3/plant-traits-v2/data/1km/chips/

settings:
  patch_size: 256
  stride: 256
  save_all: false
  overwrite: true

data:
  predictors:
    canopy_height:
      use: true
      bands: []
    modis:
      use: false
      bands: []
    soilgrids:
      use: false
      bands: []
    vodca:
      use: true
      bands: []
    worldclim:
      use: false
      bands: []

  targets:
    splot:
      use: true
      traits: []  # empty list -> use all traits
      bands: [1]  # list of trait indices to use (1-based indexing)
    gbif:
      use: false
      traits: []  # empty list -> use all traits
      bands: [1]  # list of trait indices to use (1-based indexing)
