resolution_km: 1
base_dir: "/scratch3/plant-traits-v2/data/1km"
raw_dir: "${base_dir}/raw"
ref_raster: "${raw_dir}/eo_data/canopy_height/ETH_GlobalCanopyHeight_2020_v1.tif"
trait_mapping: "/scratch3/plant-traits-v2/data/trait_mapping.json"
validity_mask: "${base_dir}/validity_mask.tif"

predictors:
  parquet_file: "${raw_dir}/eo_data/eo_predict_imputed.parquet"
  mask_file: "${raw_dir}/eo_data/eo_predict_mask.parquet"
  out_dir: "${base_dir}/predictors"
  subfolder_rules:
    ETH_: "canopy_height"
    sur_refl_: "modis"
    vodca_: "vodca"
    wc2.1_: "worldclim"
  fallback_subfolder: "soilgrids"
  nodata:
    uint8: 255
    int16: -9999
  output:
    compress: "zstd"
    zstd_level: 3
    predictor: 2
    blockxsize: 256
    blockysize: 256

# targets:
#   parquet_file: "${raw_dir}/Y.parquet"
#   source: "comb"
#   source_map:
#     g: 1
#     s: 2
#   bands:
#     1: "mean"
#     2: "source"
#   output:
#     compress: "zstd"
#     zstd_level: 3
#     blockxsize: 256
#     blockysize: 256

unnormalize:
  transform_params: "/scratch3/plant-traits-v2/data/power_transformer_params.csv"
  gbif:
    in_dir: "${base_dir}/targets/gbif"
    out_dir: "${base_dir}/targets/gbif_original"
    n_workers: 8
    output:
      zstd_level: 1
      blockxsize: 512
      blockysize: 512
      overviews: [2, 4, 8, 16, 32]
  splot:
    in_dir: "${base_dir}/targets/splot"
    out_dir: "${base_dir}/targets/splot_original"
    n_workers: 8
    output:
      zstd_level: 1
      blockxsize: 512
      blockysize: 512
      overviews: [2, 4, 8, 16, 32]

targets:
  gbif:
    in_dir: "${raw_dir}/targets/gbif"
    out_dir: "${base_dir}/targets/gbif"
    n_workers: 8
    output:
      zstd_level: 1
      blockxsize: 512
      blockysize: 512
      overviews: [2, 4, 8, 16, 32]
  splot:
    in_dir: "${raw_dir}/targets/splot"
    out_dir: "${base_dir}/targets/splot"
    gbif_ref: "${raw_dir}/targets/gbif/X13.tif"
    n_workers: 8
    output:
      zstd_level: 1
      blockxsize: 512
      blockysize: 512
      overviews: [2, 4, 8, 16, 32]
