data:
  predictors:
    canopy_height: true
    modis: false
    soilgrids: true
    vodca: true
    worldclim: true
  targets:
    gbif:
      enabled: true
      traits: [1080]
    splot: false

patch_size: 15
stride: 10
