data:
  root:
  predictors:
    canopy_height:
      use: true
      bands: []
    modis:
      use: true
      bands: []
    soilgrids:
      use: true
      bands: []
    vodca:
      use: true
      bands: []
    worldclim:
      use: true
      bands: []

  targets:
    gbif:
      use: true
      traits: [1080]
    splot:
      use: false
      traits: [1080]

patch_size: 15
stride: 10

zarr_dir: /scratch3/plant-traits-v2/data/chips/22km/
