patch_size: 15
stride: 10

data:
  root_dir: /scratch3/plant-traits-v2/data/22km/
  predictors_dir: /scratch3/plant-traits-v2/data/22km/eo_data_processed/
  predictors:
    canopy_height:
      use: true
      bands: []
    modis:
      use: true
      bands: []
    soil_grids:  # TODO: rename back to soilgrids
      use: true
      bands: []
    vodca:
      use: true
      bands: []
    worldclim:
      use: true
      bands: []

  targets:
    gbif:
      use: true
      traits: [1080]
    splot:
      use: false
      traits: [1080]

splits:
  h3_dir: /scratch3/plant-traits-v2/data/temp/h3_splits  # TODO improve

zarr_dir: /scratch3/plant-traits-v2/data/chips/22km/
