patch_size: 64
stride: 0       # 0 = non-overlapping (stride equals patch_size)
output_path: /scratch3/plant-traits-v2/data/chips/22km/val.zarr
datasets:
  canopy_height: true
  modis: false
  soilgrids: false
  vodca: false
  worldclim: false
  gbif: true
  splot: false
