paths:
  predictors_dir: /scratch3/plant-traits-v2/data/22km/eo_data_processed/
  targets_dir: /scratch3/plant-traits-v2/data/22km/targets/
  splits_file: /scratch3/plant-traits-v2/data/22km/splits/h3_splits_res1_comb_22km.gpkg
  zarr_dir: /scratch3/plant-traits-v2/data/22km/chips/

settings:
  patch_size: 15
  stride: 10        # train and val
  stride_test: 15   # test: non-overlapping (= patch_size)
  stride_all: 15
  save_all: true

data:
  root_dir: ${paths.data_root_dir}/22km/
  predictors_dir: ${paths.data_root_dir}/22km/eo_data_processed/
  predictors:
    canopy_height:
      use: true
      bands: []
    modis:
      use: true
      bands: []
    soil_grids:  # TODO: rename back to soilgrids
      use: true
      bands: []
    vodca:
      use: true
      bands: []
    worldclim:
      use: true
      bands: []

  targets:
    comb:
      use: true
      traits: []
