paths:
  predictors_dir: /scratch3/plant-traits-v2/data/1km/predictors/
  targets_dir: /scratch3/plant-traits-v2/data/1km/targets/
  splits_file: /scratch3/plant-traits-v2/data/1km/splits/h3_splits_res2_1km.gpkg
  zarr_dir: /scratch3/plant-traits-v2/data/1km/chips/

settings:
  patch_size: 128
  stride: 128
  save_all: true
  overwrite: true

data:
  predictors:
    canopy_height:
      use: true
      bands: []
    modis:
      use: false
      bands: []
    soilgrids:
      use: false
      bands: []
    vodca:
      use: true
      bands: []
    worldclim:
      use: false
      bands: []

  targets:
    splot:
      use: true
      traits: [1080]
      bands: [1]
    gbif:
      use: true
      traits: [1080]
      bands: [1]
